import Breadcrumbs from "../_components/breadcrumbs/breadcrumbs.component";

export const metadata = {
  title: "IVI Portfolio",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div className="mt-[104px] px-[4%] md:px-0 container lg:w-[57.5rem] mx-auto ">
      <h1 className="text-4xl font-bold text-center mt-20 text-black-500 py-2">
        ADMIN
      </h1>
      <Breadcrumbs />
      {children}
    </div>
  );
}
