// import './globals.css'
import '../app/styles/main.scss';
import { Footer } from './components/footer/footer.component';
import { Navbar } from './components/navbar/navbar.component';

export const metadata = {
  title: 'IVI Portfolio',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
