import '../app/_styles/main.scss';
import { Footer } from './_components/footer/footer.component';
import { Navbar } from './_components/navbar/navbar.component';
import AuthProvider from './_context/AuthContext';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/options';

export const metadata = {
  title: 'IVI Portfolio',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <AuthProvider session={session}>
          <Navbar />
          {children}
          <Footer />
        </AuthProvider>
      </body>
    </html>
  );
}
